# Generated by Django 5.1.5 on 2025-09-30 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("polls", "0002_alter_poll_winner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="banners")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "poll",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banner",
                        to="polls.poll",
                    ),
                ),
            ],
        ),
    ]
